# Generated by Django 3.0.7 on 2020-10-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
