# Generated by Django 3.0.7 on 2020-10-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0002_auto_20201009_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_info',
            new_name='StudentInfo',
        ),
    ]
